test:
  - bundle install
  - rake test

after:
  - echo 'done'

builds:
  - name: app
    dockerfile: .
    build_timeout: 300
    docker:
      name: app
      env:
        - DB_USER=dbuser
        - DB_PASS=pass
        - DB_NAME=fort_ci
        - DB_ADAPTER=mysql
    after:
      - docker exec -i app sh -c 'while ! curl -i localhost:3000; do sleep 3; echo \"waiting for api\"; done'

services:
  - name: db
    docker:
      name: db
      image: mysql:5.7
      env:
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=pass
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_DATABASE=fort_ci
      after:
        - docker logs db
        - docker exec -i db /bin/bash -c 'while ! mysql -u root --password=pass -e "select 1" ; do sleep 2; echo "waiting for mysql" ; done'
