services:
  db:
    image: mysql:5.7
    env:
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=fort_ci
    after:
      - while ! mysql -u root --password=pass -e "select 1" ; do sleep 2; echo "waiting for mysql" ; done

commands:
  test:
    - bundle install
    - rake test

  after:
    - echo 'done'

  on_success:
    - echo 'success'

  on_failure:
    - echo 'failure'

build:
  id: app
  dockerfile: .
  build_timeout: 300
  env:
    - DB_USER=dbuser
    - DB_PASS=pass
    - DB_NAME=fort_ci
    - DB_ADAPTER=mysql2
    - DB_HOST=db
  after:
    - while ! curl -i http://localhost:3001; do sleep 2; echo \"waiting for app\"; done
