test:
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  database: <%= ENV['DB_NAME'] || 'fortci_test' %>
  user: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  database: <%= ENV['DB_NAME'] || 'fortci_dev' %>
  user: <%= ENV['DB_USER'] || 'root' %>
  password: <%= ENV['DB_PASS'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

production:
  adapter: <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
