test:
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite' %>
  database: <%= ENV['DB_NAME'] || 'test.db' %>
  user: <%= ENV['DB_USER'] || '' %>
  password: <%= ENV['DB_PASS'] || '' %>

development:
  adapter: mysql2
  database: fortci_dev
  user: root

production:
  adapter: <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
