test:
  adapter: sqlite
  database: tmp/test.db

development:
  adapter: mysql2
  database: fortci_dev
  user: root

production:
  adapter: <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
