test:
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite' %>
  database: <%= ENV['DB_NAME'] || 'test.db' %>
  user: <%= ENV['DB_USER'] || '' %>
  password: <%= ENV['DB_PASS'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

development:
  adapter: <%= ENV['DB_ADAPTER'] || 'sqlite' %>
  database: <%= ENV['DB_NAME'] || 'test.db' %>
  user: <%= ENV['DB_USER'] || '' %>
  password: <%= ENV['DB_PASS'] || '' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>

production:
  adapter: <%= ENV['DB_ADAPTER'] %>
  database: <%= ENV['DB_NAME'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
